import pandas as pd

# Lista expandida com as informações dos Pokémons
dados_pokemons = [
    ["Bulbasaur", "Réptil ou Planta", "Verde"],
    ["Ivysaur", "Réptil ou Planta", "Verde"],
    ["Venusaur", "Réptil ou Planta", "Verde"],
    ["Charmander", "Ser Místico", "Vermelho"],
    ["Charmeleon", "Ser Místico", "Vermelho"],
    ["Charizard", "Ser Místico", "Laranja"],
    ["Squirtle", "Criatura Aquática", "Azul"],
    ["Wartortle", "Criatura Aquática", "Azul"],
    ["Blastoise", "Criatura Aquática", "Azul"],
    ["Caterpie", "Inseto", "Verde"],
    ["Metapod", "Inseto", "Verde"],
    ["Butterfree", "Inseto", "Roxo"],
    ["Weedle", "Inseto", "Marrom"],
    ["Kakuna", "Inseto", "Amarelo"],
    ["Beedrill", "Inseto", "Amarelo"],
    ["Pidgey", "Ave", "Marrom"],
    ["Pidgeotto", "Ave", "Marrom"],
    ["Pidgeot", "Ave", "Marrom"],
    ["Rattata", "Roedor", "Roxo"],
    ["Raticate", "Roedor", "Marrom"],
    ["Spearow", "Ave", "Marrom"],
    ["Fearow", "Ave", "Marrom"],
    ["Ekans", "Cobra ou Criatura Venenosa", "Roxo"],
    ["Arbok", "Cobra ou Criatura Venenosa", "Roxo"],
    ["Pikachu", "Roedor", "Amarelo"],
    ["Raichu", "Roedor", "Laranja"],
    ["Sandshrew", "Toupeira ou Tartaruga", "Amarelo"],
    ["Sandslash", "Toupeira ou Tartaruga", "Amarelo"],
    ["Nidoran♀", "Criatura Venenosa", "Roxo"],
    ["Nidorina", "Criatura Venenosa", "Roxo"],
    ["Nidoqueen", "Criatura Venenosa", "Azul"],
    ["Nidoran♂", "Criatura Venenosa", "Roxo"],
    ["Nidorino", "Criatura Venenosa", "Roxo"],
    ["Nidoking", "Criatura Venenosa", "Roxo"],
    ["Clefairy", "Criatura Mágica", "Rosa"],
    ["Clefable", "Criatura Mágica", "Rosa"],
    ["Vulpix", "Ser Místico", "Laranja"],
    ["Ninetales", "Ser Místico", "Amarelo"],
    ["Jigglypuff", "Criatura Mágica", "Rosa"],
    ["Wigglytuff", "Criatura Mágica", "Rosa"],
    ["Zubat", "Morcego", "Roxo"],
    ["Golbat", "Morcego", "Roxo"],
    ["Oddish", "Planta", "Azul"],
    ["Gloom", "Planta", "Azul"],
    ["Vileplume", "Planta", "Azul"],
    ["Paras", "Inseto", "Laranja"],
    ["Parasect", "Inseto", "Laranja"],
    ["Venonat", "Inseto", "Roxo"],
    ["Venomoth", "Inseto", "Roxo"],
    ["Diglett", "Toupeira", "Marrom"],
    ["Dugtrio", "Toupeira", "Marrom"],
    ["Meowth", "Felino", "Amarelo"],
    ["Persian", "Felino", "Amarelo"],
    ["Psyduck", "Pato", "Amarelo"],
    ["Golduck", "Pato", "Azul"],
    ["Mankey", "Macaco", "Marrom"],
    ["Primeape", "Macaco", "Marrom"],
    ["Growlithe", "Cachorro", "Laranja"],
    ["Arcanine", "Cachorro", "Laranja"],
    ["Poliwag", "Tubarão", "Azul"],
    ["Poliwhirl", "Tubarão", "Azul"],
    ["Poliwrath", "Tubarão", "Azul"],
    ["Abra", "Ser Mental", "Amarelo"],
    ["Kadabra", "Ser Mental", "Amarelo"],
    ["Alakazam", "Ser Mental", "Amarelo"],
    ["Machop", "Guerreiro", "Azul"],
    ["Machoke", "Guerreiro", "Azul"],
    ["Machamp", "Guerreiro", "Azul"],
    ["Bellsprout", "Planta", "Verde"],
    ["Weepinbell", "Planta", "Verde"],
    ["Victreebel", "Planta", "Verde"],
    ["Tentacool", "Criatura Aquática", "Azul"],
    ["Tentacruel", "Criatura Aquática", "Azul"],
    ["Geodude", "Criatura de Pedra", "Marrom"],
    ["Graveler", "Criatura de Pedra", "Marrom"],
    ["Golem", "Criatura de Pedra", "Marrom"],
    ["Ponyta", "Cavalo", "Laranja"],
    ["Rapidash", "Cavalo", "Laranja"],
    ["Slowpoke", "Criatura Aquática", "Rosa"],
    ["Slowbro", "Criatura Aquática", "Rosa"],
    ["Magnemite", "Robô", "Cinza"],
    ["Magneton", "Robô", "Cinza"],
    ["Farfetch'd", "Ave", "Marrom"],
    ["Doduo", "Ave", "Marrom"],
    ["Dodrio", "Ave", "Marrom"],
    ["Seel", "Foca", "Branco"],
    ["Dewgong", "Foca", "Branco"],
    ["Grimer", "Lodo", "Roxo"],
    ["Muk", "Lodo", "Roxo"],
    ["Shellder", "Criatura Aquática", "Roxo"],
    ["Cloyster", "Criatura Aquática", "Roxo"],
    ["Gastly", "Espírito", "Roxo"],
    ["Haunter", "Espírito", "Roxo"],
    ["Gengar", "Espírito", "Roxo"],
    ["Eevee", "Mamífero", "Marrom"],
    ["Vaporeon", "Ser Místico", "Azul"],
    ["Jolteon", "Ser Místico", "Amarelo"],
    ["Flareon", "Ser Místico", "Laranja"],
    ["Espeon", "Ser Mental", "Roxo"],
    ["Umbreon", "Ser Místico", "Preto"],
    ["Leafeon", "Planta", "Verde"],
    ["Glaceon", "Ser Místico", "Azul"],
    ["Sylveon", "Fada", "Rosa"],
    ["Pikachu", "Roedor", "Amarelo"],
    ["Mankey", "Macaco", "Marrom"],
    ["Primeape", "Macaco", "Marrom"],
    ["Raichu", "Roedor", "Amarelo"],
    ["Snorlax", "Mamífero", "Verde"],
    ["Mewtwo", "Ser Mental", "Roxo"],
    ["Mew", "Místico", "Rosa"],
    ["Chikorita", "Planta", "Verde"],
    ["Bayleef", "Planta", "Verde"],
    ["Meganium", "Planta", "Verde"],
    ["Cyndaquil", "Ser Místico", "Azul"],
    ["Quilava", "Ser Místico", "Azul"],
    ["Typhlosion", "Ser Místico", "Azul"],
    ["Totodile", "Criatura Aquática", "Azul"],
    ["Croconaw", "Criatura Aquática", "Azul"],
    ["Feraligatr", "Criatura Aquática", "Azul"]
]

# Criando o DataFrame
df_pokemons = pd.DataFrame(dados_pokemons, columns=["Nome", "Tipo de Animal", "Cor"])

# Exibindo a tabela
print(df_pokemons)

# Salvando em arquivo CSV
df_pokemons.to_csv("tabela_pokemons_expandidos.csv", index=False)
